apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
spec:
  replicas: 2  # Specifies the number of instances
  selector:
    matchLabels:
      app: url-shortener-tech-test-main
  template:
    metadata:
      labels:
        app: url-shortener-tech-test-main
    spec:
      containers:
      - name: url-shortener-app
        image: geetakukreja/url_shortener:image1
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: url-shortener-config
