apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
spec:
  replicas: 2  # Specifies the number of instances
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: geetakukreja/url-shortener:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: url-shortener-config
