version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: url_shortener
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    
  app:
    build: .
    container_name: url_shortener_app
    ports:
    - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/url_shortener
    depends_on:
      - mongodb

volumes:
  mongo_data:
