version: '3'
services:
  app:
    build: .
    container_name: url_shortener_app
    ports:
    - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://practicegr17:GYBI6J3idUPaaCL2@urlshortener.i8u0d.mongodb.net/?retryWrites=true&w=majority&appName=URLShortener
    # command: uvicorn server:app --host 0.0.0.0 --port 5000


