version: '3'
services:
  app:
    build: .
    container_name: url_shortener_app
    ports:
    - "8000:8000"
    env_file:
      - .env
    # command: uvicorn server:app --host 0.0.0.0 --port 5000
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: url_shortener_redis
    command: redis-server --appendonly yes --save 60 1 --save 300 10
    ports:
      - "6379:6379"  # Expose Redis on default port 6379
    volumes:
      - redis_data:/data  # Mount a volume to persist Redis data

volumes:
  redis_data:


